apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-mjclouds-com
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
      - dns01:
          webhook:
            groupName: acme.mjclouds.com
            solverName: alidns-solver
            config:
              regionId: ""
              accessTokenSecretRef:
                name: alidns-secret
                key: mjclouds-access-key
              secretKeySecretRef:
                name: alidns-secret
                key: mjclouds-secret-key
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-juanji-tech
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
      - dns01:
          webhook:
            groupName: acme.mjclouds.com
            solverName: alidns-solver
            config:
              regionId: ""
              accessTokenSecretRef:
                name: alidns-secret
                key: juanji-access-key
              secretKeySecretRef:
                name: alidns-secret
                key: juanji-secret-key